agentType: prometheus
type: exporter

name: redis_collector_plugin
version: 1.0.0

category: 数据库
params:
    - redis_host
    - redis_port
    - redis_password
    - exporter_host
    - exporter_port
    - exporter_uri
